version: '3'
services:
  web:
    image: 'htmlgraphic/apache:latest' # PHP v7.3.2-3+ubuntu18.04.1+deb.sury.org+1
    container_name: apache
    volumes:
      - '~/SITES/docker:/data' # <- Change to preferred local working dir
     #- '/c/Users/southpark/docker:/data'
    links:
      - 'db:mysql'
    ports:
      - '80:80'
      - '443:443'
    env_file:
      - .env
  db:
    image: 'mysql:5.7.25'
    container_name: apache_db
    volumes:
      - 'db-data:/var/lib/mysql'
    ports:
      - '3306:3306'
    env_file:
      - .env
    command: mysqld --sql_mode="ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
  phpmyadmin:
    image: 'marvambass/phpmyadmin:latest'
    container_name: apache_phpmyadmin
    ports:
      - '8080:443'
    volumes:
      - /tmp
    links:
      - 'db:mysql'
volumes:
  db-data:
